all: help

install:
	@pip install -r requirements.txt

start:
	@flask run

help:
	@echo
	@echo Pokedex
	@echo -------
	@echo "make install    Run the installation"
	@echo "make start      Start the app"
	@echo

.PHONY: install start
